---
# tasks file for Debian flavour

# Adjust locales
- name: Ensure proper locales
  locale_gen: name={{ item }} state=present
  with_items: "{{ locales_list }}"
  when: locales_install

# Update kernel
- name: Update kernel to 4.x version using backport
  include: upgrade_kernel4_jessie.yml
  when: upgrade_kernel

# Install and configure ODBC
- name: Install and configure odbc
  include: odbc.yml
  when: odbc_install

# Freeswitch repo
- name: Add FreeSwitch Repo Signing key
  apt_key: url=https://files.freeswitch.org/repo/deb/debian/freeswitch_archive_g0.pub state=present

- name: Add FreeSwitch apt repository (1.6) (Debian 8/Jessie)
  apt_repository:
    repo: deb http://files.freeswitch.org/repo/deb/freeswitch-1.6/ jessie main
    state: present
    filename: 'freeswitch'

- name: Update APT Cache
  apt: update_cache=yes

- name: Ensure tzdata is installed
  apt: name=tzdata state=latest
  when: ntp_install

# Install base packages
- name: Install base packages
  apt: name={{ item }} state=latest
  with_items: "{{ basepackages_list }}"
  when: basepackages_install

### source of systemd-timesynd : https://github.com/debops/ansible-ntp
- name: Ensure that alternative daemons/programs are not installed
  apt:
    name: '{{ item }}'
    state: absent
    purge: True
  with_flattened:
    - ntpdate
    - ntp
    - openntpd
  when: ntp_install

- name: Manage systemd-timesyncd state
  service:
    name: 'systemd-timesyncd'
    state: started
    enabled: True
  when: ntp_install

# Configure systemd-timesyncd
- name: Include systemd-timesyncd configuration
  include: systemd-timesyncd.yml
  when: ntp_install

- name: Timezone configuration
  include: timezone.yml
  when: (ntp_timezone|d() and ntp_install)

# Install unbound
- name: Include unbound installation / configuration
  include: unbound.yml
  when: unbound_install

# Install FreeSwitch
- name: Install FreeSwitch
  apt: name={{ item }} state=latest
  with_items: "{{ freeswitch_packages }}"

- name: Copy FreeSwitch configuration files.
  template:
    src: "{{ freeswitch_config_template_dir }}/{{ item }}.j2"
    dest: "{{ freeswitch_conf_dir }}/{{ item }}"
    backup: yes
  with_items: "{{ freeswitch_config_list }}"
  when: freeswitch_install_conf

- name: Make sure FS script dir exists
  file:
    path: '{{ freeswitch_script_template_dir }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Copy FreeSwitch script files.
  template:
    src: "{{ freeswitch_script_template_dir }}/{{ item }}"
    dest: "{{ freeswitch_script_dir }}/{{ item }}"
    backup: yes
  with_items: "{{ freeswitch_script_list }}"
  when: freeswitch_install_script

- name: Make sure FreeSwitch is started and configure it to run at boot.
  service: name=freeswitch state=started enabled=yes

# FreeSwitch symlinks
- name: Make sure /usr/local/freeswitch dir exists
  file:
    path: '/usr/local/freeswitch'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: freeswitch_symlinks

- name: Make sure /usr/local/freeswitch/bin dir exists
  file:
    path: '/usr/local/freeswitch/bin'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: freeswitch_symlinks

- name: Create symlinks like default FS install documention
  file:
    src: '{{ item.src }}'
    dest: '/usr/local/freeswitch/{{ item.dest }}'
    force: '{{ item.force }}'
    state: 'link'
  with_items:
    - { src: '/usr/bin/freeswitch', dest: 'bin/freeswitch', force: no }
    - { src: '/usr/bin/fs_cli', dest: 'bin/fs_cli', force: no }
    - { src: '/usr/bin/fs_encode', dest: 'bin/fs_encode', force: no }
    - { src: '/usr/bin/fs_ivrd', dest: 'bin/fs_ivrd', force: no }
    - { src: '/usr/bin/fsxs', dest: 'bin/fsxs', force: no }
    - { src: '/usr/bin/tone2wav', dest: 'bin/tone2wave', force: no }
    - { src: '/usr/bin/gentls_cert', dest: 'bin/gentls_cert', force: no }
    - { src: '/etc/freeswitch', dest: 'conf', force: no }
    - { src: '/var/lib/freeswitch/db', dest: 'db', force: no }
    - { src: '/var/lib/freeswitch/images', dest: 'images', force: no }
    - { src: '/var/lib/freeswitch/recordings', dest: 'recordings', force: no }
    - { src: '/var/lib/freeswitch/storage', dest: 'storage', force: no }
    - { src: '/var/log/freeswitch', dest: 'log', force: no }
    - { src: '/var/run/freeswitch', dest: 'run', force: no }
    - { src: '/etc/freeswitch/tls', dest: 'certs', force: no }
  when: freeswitch_symlinks

# g729
- name: mod_bcg729 codec installation process
  include: g729.yml
  when: freeswitch_g729_install

# mod_fail2ban
# https://freeswitch.org/confluence/display/FREESWITCH/Fail2Ban
# https://freeswitch.org/confluence/display/FREESWITCH/mod_fail2ban
- name: install fail2ban
  apt: name=fail2ban state=latest
  when: fail2ban_install == true

- copy: src={{ fail2ban_local_jail }} dest={{ fail2ban_local_jail_file }}
  when: fail2ban_install == true
- copy: src={{ fail2ban_fs }} dest={{ fail2ban_filter_dir }}/freeswitch.conf
  when: fail2ban_install == true
- copy: src={{ fail2ban_dos_fs }} dest={{ fail2ban_filter_dir }}/freeswitch-dos.conf
  when: fail2ban_install == true

# monit

# munin
- name: check if munin-node is installed
  apt: name=munin-node state=latest
  register: apt_munin_node_check
  ignore_errors: yes
  when: munin_node_install

- include: munin-plugin.yml
  when: munin_node_install

# sngrep
- name: Sngrep installation process
  include: sngrep.yml
  when: sngrep_install

